### ISSUE TITLE
The browser can't show three colors

### ISSUE THREAD

**Issue by zting135** [bhofmei/jbplugin-methylation#15]
![image](https://user-images.githubusercontent.com/37932087/41817582-92ed1ee8-77d0-11e8-8ec5-539186a2c806.png)

I try to use this plugin into my JBrowse. First, when I run the test data in the MethylationPlugin, I don't get any plot in MethylPlot style. And only one color line in MethylXYPlot style. Can you help me?

Thanks!

**Comment by bhofmei** [comment]
Sorry for the delayed response, I've been on vacation. 

Are there any error messages in the browser console?

**Comment by bhofmei** [comment]
Also, what version of JBrowse are you using?
