### ISSUE TITLE
jbrowse_15.3 issue

### ISSUE THREAD

**Issue by EtienneBucher** [bhofmei/jbplugin-methylation#16]
Hi, 
I have tried to install the MethylationPlugin under jbrowse 1.15.3. Unfortunately the tracks don't properly display only showing grey bars saying "loading" (see attached screenshot). Only the HTML Methylation tracks display properly. I get the same result under MacOSX and Ubuntu.

<img width="798" alt="screenshot" src="https://user-images.githubusercontent.com/43307636/45592453-2c905e00-b96e-11e8-8d32-4c3041d1f7c1.png">

**Comment by EtienneBucher** [comment]
I checked the javascript console and there is the following error:
TypeError: Cannot read property 'toLowerCase' of undefined TypeError: Cannot read property 'toLowerCase' of undefined at fastDeclareClass.get

**Comment by bhofmei** [comment]
Thanks for that info. There’s been so many jbrowse updates recently it’s been hard to stay on top of testing. I’ll look into that error ASAP. 

Brigitte

**Comment by bhofmei** [comment]
I think I fixed it. Let me know if you still have problems.

**Comment by EtienneBucher** [comment]
Thank you for your fast response!
Unfortunately I am still getting the same error:
TypeError: Cannot read property 'toLowerCase' of undefined TypeError: Cannot read property 'toLowerCase' of undefined

**Comment by bhofmei** [comment]
Did you hit pull, rerun “./setup.sh”, and clear your cache?

Brigitte

**Comment by EtienneBucher** [comment]
Yes, that did it.
Thank you very much for making this plugin! We use it A LOT ;-)
Best wishes,
Etienne
