### ISSUE TITLE
Problem with Jbrowse 1.16.6

### ISSUE THREAD

**Issue by yloemie** [bhofmei/jbplugin-methylation#18]
Hi,

first thanks for your work. I have read (after I have found that my track didn't appear) that you have troubles with recent Jbrowse versions. So what is the last version I can use for your plugin?

By the way my error is very strange : 
HTTP 200 when fetching "url to the bigwig"

Error 200 is actually not an error.

In the console it says when I start JBrowse : "MethylationPlugin starting - v3.3.2"  like other plugins.

Thanks,

Yann

**Comment by bhofmei** [comment]
I currently use my plugin with JBrowse v1.16.1 without issue and don't expect there to be a problem with later versions of 1.16.

Are you able to see the test dataset?

**Comment by yloemie** [comment]
Hi,

yes it works, so I will check why my dataset doesn't work.
I guess you can close the "issue".

Thanks, best.

**Comment by yloemie** [comment]
Hi again,
I fixed my bug, it seems that the name of the file was the problem. I didn't go into your code but it's maybe due to the text parsing you do (by adding cg, chg or chh). My original name was : test_JHCC292.R1_bismark_bt2_pe.deduplicated.CX_report_noZero.txt.bw[.cg, .chh .chg] and changing to test.bw fixed the bug.

Best,

Yann
