### ISSUE TITLE
plugin is not adding a new track while selecting

### ISSUE THREAD

**Issue by rbpisupati** [bhofmei/jbplugin-methylation#8]
Hi, 

Can you provide the dependencies required for proper installation of the package?

Thanks, 
Rahul

**Comment by rbpisupati** [comment]
not working also while using the test url!

**Comment by bhofmei** [comment]
There are no dependencies required for viewing. I'm not sure why the test url won't work since it works for me. Perhaps it's a permission error? Is there a console error message which could point me to the cause?

There are dependencies for creating new tracks. Except for python and python packages, the dependencies are included. You will want to create symbolic links based on your operating system and add it to your path.

**Comment by rbpisupati** [comment]
I dont think it is the permission error! I have put the plugin in the default directory! 

![screen shot 2017-08-10 at 5 20 40 pm](https://user-images.githubusercontent.com/11807889/29177946-663f652a-7df0-11e7-86eb-5e87cadf3a4a.png)

Here are the log messages 

10.60.33.193 - - [10/Aug/2017:15:26:08 +0000] "GET /MethylationPlugin/View/Track/MethylHTMLPlot.js HTTP/1.1" 404 550 "http://jupyter.sci.gmi.oeaw.ac.at/index.html?data=plugins%2FMethylationPlugin%2Ftest%2Fdata&loc=Chr5%3A1..50001&tracks=DNA%2Cgenes&highlight=" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
10.60.33.193 - - [10/Aug/2017:15:26:09 +0000] "GET /MethylationPlugin/View/Track/Wiggle/MethylPlot.js HTTP/1.1" 404 553 "http://jupyter.sci.gmi.oeaw.ac.at/index.html?data=plugins%2FMethylationPlugin%2Ftest%2Fdata&loc=Chr5%3A1..50001&tracks=DNA%2Cgenes&highlight=" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"

No error messages are being recorded!

**Comment by bhofmei** [comment]
I'm not sure why you aren't getting more useful error messages but the 404 status code means the resource wasn't found. Have you added the plugin to __jbrowse.conf__ or __jbrowse_conf.json__? Did you include the location parameter as well? (I know it should  be able to find the default path without specifying the location, but it has never worked properly for me. I always have to specify the location)

**Comment by rbpisupati** [comment]
yes, I did add them to both the conf files. I added the lines you have mentioned in readme!

**Comment by bhofmei** [comment]
It's a bad idea to add any plugin to multiple configuration files. It can cause issues with loading.

This could also be a caching issue if you changed anything in the configuration file and didn't reload the cache. Have you tried clearing your browser cache?

Talking to someone who knows more about the JBrowse infrastructure than me, it really seems like the plugin isn't being declared correctly. Could you include the jbrowse.conf and/or jbrowse_conf.json plugin declarations?

**Comment by rbpisupati** [comment]
Yes, I tried adding it in one and didnt work. So added it in both but removed one of it now!

I think the problem at first was that javascript and bower were not installed in the system. But even after installation there was this caching issue which was the problem. Now after removing the cache it is working good! 

Thanks Brigitte!

**Comment by bhofmei** [comment]
Bower shouldn't have been necessary (most of the plugin was written without bower installed on my computer and the server which runs my lab's JBrowse doesn't have npm installed on it). Bower is only used to run the test suite (viewing the test data is independent of that). 

But I'm really glad it's working now!!!
